// Code generated by internal/codegen/webhooks/main.go; DO NOT EDIT.

package webhooks_gen

import (
	"encoding/json"

	notificationsapi "github.com/catenaclearing/catena-sdk-go/gen/notifications"
)

var NotificationsDecoders = map[string]func(json.RawMessage) (any, error){
	"connection.created":        decodeBaseConnectionEvent,
	"connection.staled":         decodeBaseConnectionEvent,
	"execution.failed":          decodeBaseExecutionEvent,
	"execution.staled":          decodeBaseExecutionEvent,
	"hos_availability.added":    decodeBaseHosAvailability,
	"hos_availability.modified": decodeBaseHosAvailability,
	"hos_availability.removed":  decodeBaseTelematicsEvent,
	"hos_event.added":           decodeBaseHosEvent,
	"hos_event.modified":        decodeBaseHosEvent,
	"hos_event.removed":         decodeBaseTelematicsEvent,
	"hos_violation.added":       decodeBaseHosViolation,
	"hos_violation.modified":    decodeBaseHosViolation,
	"hos_violation.removed":     decodeBaseTelematicsEvent,
	"ifta_summary.added":        decodeBaseIftaSummary,
	"ifta_summary.modified":     decodeBaseIftaSummary,
	"ifta_summary.removed":      decodeBaseTelematicsEvent,
	"invitation.accepted":       decodeBaseInvitationEvent,
	"invitation.created":        decodeBaseInvitationEvent,
	"invitation.declined":       decodeBaseInvitationEvent,
	"invitation.deleted":        decodeBaseInvitationEvent,
	"invitation.expired":        decodeBaseInvitationEvent,
	"invitation.rejected":       decodeBaseInvitationEvent,
	"invitation.sent":           decodeBaseInvitationEvent,
	"invitation.viewed":         decodeBaseInvitationEvent,
	"schedule.deactivated":      decodeBaseScheduleEvent,
	"share_agreement.created":   decodeBaseShareAgreementEvent,
	"share_agreement.deleted":   decodeBaseShareAgreementEvent,
	"share_agreement.updated":   decodeBaseShareAgreementEvent,
	"tsp.created":               decodeBaseTspEvent,
	"user.added":                decodeBaseUser,
	"user.modified":             decodeBaseUser,
	"user.removed":              decodeBaseTelematicsEvent,
	"vehicle.added":             decodeBaseVehicle,
	"vehicle.modified":          decodeBaseVehicle,
	"vehicle.removed":           decodeBaseTelematicsEvent,
	"vehicle_location.added":    decodeBaseVehicleLocation,
	"webhook.created":           decodeBaseWebhookEvent,
	"webhook.deleted":           decodeBaseWebhookEvent,
	"webhook.staled":            decodeBaseWebhookEvent,
	"webhook.updated":           decodeBaseWebhookEvent,
}

func decodeBaseConnectionEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseConnectionEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseExecutionEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseExecutionEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseHosAvailability(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseHosAvailability
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseHosEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseHosEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseHosViolation(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseHosViolation
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseIftaSummary(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseIftaSummary
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseInvitationEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseInvitationEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseScheduleEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseScheduleEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseShareAgreementEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseShareAgreementEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseTelematicsEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseTelematicsEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseTspEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseTspEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseUser(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseUser
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseVehicle(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseVehicle
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseVehicleLocation(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseVehicleLocation
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func decodeBaseWebhookEvent(data json.RawMessage) (any, error) {
	var out []notificationsapi.BaseWebhookEvent
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	return out, nil
}
