package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
)

func main() {
	rootDir, err := os.Getwd()
	if err != nil {
		log.Fatalf("Failed to get working directory: %v", err)
	}

	// 1. Discover paginated operations from OpenAPI specs
	specsDir := filepath.Join(rootDir, "specs")
	ops, err := discoverPaginatedOperations(specsDir)
	if err != nil {
		log.Fatalf("Failed to discover operations: %v", err)
	}

	// 2. Inspect generated Go code to refine details
	ops, err = inspectGeneratedCode(rootDir, ops)
	if err != nil {
		log.Fatalf("Failed to inspect generated code: %v", err)
	}

	// 3. Group by service
	opsByService := make(map[string][]PaginatedOperation)
	for _, op := range ops {
		opsByService[op.Service] = append(opsByService[op.Service], op)
	}

	// 4. Generate code
	outDir := filepath.Join(rootDir, "pagination")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		log.Fatalf("Failed to create output directory: %v", err)
	}

	for service, serviceOps := range opsByService {
		var buf bytes.Buffer

		hasTime := false
		for _, op := range serviceOps {
			for _, p := range op.RequiredParams {
				if p.Type == "time.Time" {
					hasTime = true
					break
				}
			}
			if hasTime {
				break
			}
			for _, p := range op.OptionalParams {
				if p.Type == "time.Time" {
					hasTime = true
					break
				}
			}
			if hasTime {
				break
			}
		}

		// Header
		fmt.Fprintf(&buf, "// Code generated by catena-sdk-go pagination generator; DO NOT EDIT.\n\n")
		fmt.Fprintf(&buf, "package pagination\n\n")
		fmt.Fprintf(&buf, "import (\n")
		fmt.Fprintf(&buf, "\t\"context\"\n")
		if hasTime {
			fmt.Fprintf(&buf, "\t\"time\"\n")
		}
		fmt.Fprintf(&buf, "\n")
		fmt.Fprintf(&buf, "\tcatena \"github.com/catenaclearing/catena-sdk-go\"\n")
		fmt.Fprintf(&buf, "\t%sapi \"github.com/catenaclearing/catena-sdk-go/gen/%s\"\n", service, service)
		fmt.Fprintf(&buf, "\t\"github.com/catenaclearing/catena-sdk-go/internal/pagination\"\n")
		fmt.Fprintf(&buf, ")\n\n")

		for _, op := range serviceOps {
			if err := tmpl.Execute(&buf, op); err != nil {
				log.Fatalf("Failed to execute template for %s: %v", op.OperationID, err)
			}
			buf.WriteString("\n")
		}

		// Format code
		src, err := format.Source(buf.Bytes())
		if err != nil {
			log.Printf("Warning: failed to format code for %s: %v", service, err)
			src = buf.Bytes()
		}

		outFile := filepath.Join(outDir, "pagination_"+service+".go")
		if err := os.WriteFile(outFile, src, 0644); err != nil {
			log.Fatalf("Failed to write file %s: %v", outFile, err)
		}
		fmt.Printf("Generated %s\n", outFile)
	}
}
