// Code generated by catena-sdk-go pagination generator; DO NOT EDIT.

package pagination

import (
	"context"
	"time"

	catena "github.com/catenaclearing/catena-sdk-go"
	telematicsapi "github.com/catenaclearing/catena-sdk-go/gen/telematics"
	"github.com/catenaclearing/catena-sdk-go/internal/pagination"
)

// ListGroupMessagesPaginationOptions holds the options for the ListGroupMessages paginated operation.
type ListGroupMessagesPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	SenderIds         *[]string
	GroupIds          *[]string
	SourceSenderIds   *[]string
	SourceGroupIds    *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListGroupMessagesEach iterates over all items in the ListGroupMessages operation.
func ListGroupMessagesEach(c *catena.Client, ctx context.Context, opts ListGroupMessagesPaginationOptions, yield func(telematicsapi.GroupMessageRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.GroupMessageRead, string, error) {
		req := c.Telematics().DriversUsersAPI.ListGroupMessages(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.SenderIds != nil {
			req = req.SenderIds(*opts.SenderIds)
		}
		if opts.GroupIds != nil {
			req = req.GroupIds(*opts.GroupIds)
		}
		if opts.SourceSenderIds != nil {
			req = req.SourceSenderIds(*opts.SourceSenderIds)
		}
		if opts.SourceGroupIds != nil {
			req = req.SourceGroupIds(*opts.SourceGroupIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosAvailabilitiesPaginationOptions holds the options for the ListHosAvailabilities paginated operation.
type ListHosAvailabilitiesPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	IncludeSourceData *bool
	DriverIds         *[]string
	VehicleIds        *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosAvailabilitiesEach iterates over all items in the ListHosAvailabilities operation.
func ListHosAvailabilitiesEach(c *catena.Client, ctx context.Context, opts ListHosAvailabilitiesPaginationOptions, yield func(telematicsapi.HosAvailabilityRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.HosAvailabilityRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.ListHosAvailabilities(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListTimezonesReferencePaginationOptions holds the options for the ListTimezonesReference paginated operation.
type ListTimezonesReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListTimezonesReferenceEach iterates over all items in the ListTimezonesReference operation.
func ListTimezonesReferenceEach(c *catena.Client, ctx context.Context, opts ListTimezonesReferencePaginationOptions, yield func(telematicsapi.RefTimezoneCode) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefTimezoneCode, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListTimezonesReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListRulesetsReferencePaginationOptions holds the options for the ListRulesetsReference paginated operation.
type ListRulesetsReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListRulesetsReferenceEach iterates over all items in the ListRulesetsReference operation.
func ListRulesetsReferenceEach(c *catena.Client, ctx context.Context, opts ListRulesetsReferencePaginationOptions, yield func(telematicsapi.RefHosRuleset) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefHosRuleset, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListRulesetsReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// GetHosEventAttachmentsPaginationOptions holds the options for the GetHosEventAttachments paginated operation.
type GetHosEventAttachmentsPaginationOptions struct {
	// HosEventId is a required parameter.
	HosEventId        string
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	IncludeSourceData *bool
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// GetHosEventAttachmentsEach iterates over all items in the GetHosEventAttachments operation.
func GetHosEventAttachmentsEach(c *catena.Client, ctx context.Context, opts GetHosEventAttachmentsPaginationOptions, yield func(telematicsapi.HosEventAttachmentRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.HosEventAttachmentRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.GetHosEventAttachments(ctx, opts.HosEventId)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosViolationCodesReferencePaginationOptions holds the options for the ListHosViolationCodesReference paginated operation.
type ListHosViolationCodesReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosViolationCodesReferenceEach iterates over all items in the ListHosViolationCodesReference operation.
func ListHosViolationCodesReferenceEach(c *catena.Client, ctx context.Context, opts ListHosViolationCodesReferencePaginationOptions, yield func(telematicsapi.RefHosViolationCode) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefHosViolationCode, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListHosViolationCodesReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosDailySnapshotsPaginationOptions holds the options for the ListHosDailySnapshots paginated operation.
type ListHosDailySnapshotsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	DriverIds         *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosDailySnapshotsEach iterates over all items in the ListHosDailySnapshots operation.
func ListHosDailySnapshotsEach(c *catena.Client, ctx context.Context, opts ListHosDailySnapshotsPaginationOptions, yield func(telematicsapi.HosDailySnapshotRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.HosDailySnapshotRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.ListHosDailySnapshots(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListFleetSummariesPaginationOptions holds the options for the ListFleetSummaries paginated operation.
type ListFleetSummariesPaginationOptions struct {
	FleetIds     *[]string
	FleetRefs    *[]string
	ConnectionId *string
	SortBy       *string
	SortOrder    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListFleetSummariesEach iterates over all items in the ListFleetSummaries operation.
func ListFleetSummariesEach(c *catena.Client, ctx context.Context, opts ListFleetSummariesPaginationOptions, yield func(telematicsapi.FleetSummary) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.FleetSummary, string, error) {
		req := c.Telematics().AnalyticsAPI.ListFleetSummaries(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListVehicleSummariesPaginationOptions holds the options for the ListVehicleSummaries paginated operation.
type ListVehicleSummariesPaginationOptions struct {
	FleetIds     *[]string
	FleetRefs    *[]string
	ConnectionId *string
	VehicleIds   *[]string
	SourceIds    *[]string
	SortBy       *string
	SortOrder    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListVehicleSummariesEach iterates over all items in the ListVehicleSummaries operation.
func ListVehicleSummariesEach(c *catena.Client, ctx context.Context, opts ListVehicleSummariesPaginationOptions, yield func(telematicsapi.VehicleSummary) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.VehicleSummary, string, error) {
		req := c.Telematics().AnalyticsAPI.ListVehicleSummaries(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListVehicleLiveLocationsPaginationOptions holds the options for the ListVehicleLiveLocations paginated operation.
type ListVehicleLiveLocationsPaginationOptions struct {
	FleetIds     *[]string
	FleetRefs    *[]string
	ConnectionId *string
	DriverIds    *[]string
	VehicleIds   *[]string
	SourceIds    *[]string
	SortBy       *string
	SortOrder    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListVehicleLiveLocationsEach iterates over all items in the ListVehicleLiveLocations operation.
func ListVehicleLiveLocationsEach(c *catena.Client, ctx context.Context, opts ListVehicleLiveLocationsPaginationOptions, yield func(telematicsapi.VehicleLiveLocation) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.VehicleLiveLocation, string, error) {
		req := c.Telematics().AnalyticsAPI.ListVehicleLiveLocations(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListDriverSafetyEventsPaginationOptions holds the options for the ListDriverSafetyEvents paginated operation.
type ListDriverSafetyEventsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	DriverIds         *[]string
	VehicleIds        *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListDriverSafetyEventsEach iterates over all items in the ListDriverSafetyEvents operation.
func ListDriverSafetyEventsEach(c *catena.Client, ctx context.Context, opts ListDriverSafetyEventsPaginationOptions, yield func(telematicsapi.DriverSafetyEventRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.DriverSafetyEventRead, string, error) {
		req := c.Telematics().SafetyDriverBehaviorAPI.ListDriverSafetyEvents(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListFuelTransactionsPaginationOptions holds the options for the ListFuelTransactions paginated operation.
type ListFuelTransactionsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	DriverIds         *[]string
	SourceDriverIds   *[]string
	VehicleIds        *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListFuelTransactionsEach iterates over all items in the ListFuelTransactions operation.
func ListFuelTransactionsEach(c *catena.Client, ctx context.Context, opts ListFuelTransactionsPaginationOptions, yield func(telematicsapi.FuelTransactionRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.FuelTransactionRead, string, error) {
		req := c.Telematics().MaintenanceVehicleHealthAPI.ListFuelTransactions(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.SourceDriverIds != nil {
			req = req.SourceDriverIds(*opts.SourceDriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListVehicleLocationsPaginationOptions holds the options for the ListVehicleLocations paginated operation.
type ListVehicleLocationsPaginationOptions struct {
	OnlyLatest        *bool
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	DriverIds         *[]string
	VehicleIds        *[]string
	IncludeSourceData *bool
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListVehicleLocationsEach iterates over all items in the ListVehicleLocations operation.
func ListVehicleLocationsEach(c *catena.Client, ctx context.Context, opts ListVehicleLocationsPaginationOptions, yield func(telematicsapi.VehicleLocationRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.VehicleLocationRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListVehicleLocations(ctx)
		if opts.OnlyLatest != nil {
			req = req.OnlyLatest(*opts.OnlyLatest)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListEngineStatusesPaginationOptions holds the options for the ListEngineStatuses paginated operation.
type ListEngineStatusesPaginationOptions struct {
	OnlyLatest        *bool
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	DriverIds         *[]string
	VehicleIds        *[]string
	IncludeSourceData *bool
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListEngineStatusesEach iterates over all items in the ListEngineStatuses operation.
func ListEngineStatusesEach(c *catena.Client, ctx context.Context, opts ListEngineStatusesPaginationOptions, yield func(telematicsapi.EngineStatusRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.EngineStatusRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListEngineStatuses(ctx)
		if opts.OnlyLatest != nil {
			req = req.OnlyLatest(*opts.OnlyLatest)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosMalfunctionCodesReferencePaginationOptions holds the options for the ListHosMalfunctionCodesReference paginated operation.
type ListHosMalfunctionCodesReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosMalfunctionCodesReferenceEach iterates over all items in the ListHosMalfunctionCodesReference operation.
func ListHosMalfunctionCodesReferenceEach(c *catena.Client, ctx context.Context, opts ListHosMalfunctionCodesReferencePaginationOptions, yield func(telematicsapi.RefHosMalfunctionCode) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefHosMalfunctionCode, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListHosMalfunctionCodesReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListTrailerSummariesPaginationOptions holds the options for the ListTrailerSummaries paginated operation.
type ListTrailerSummariesPaginationOptions struct {
	FleetIds     *[]string
	FleetRefs    *[]string
	ConnectionId *string
	TrailerIds   *[]string
	SourceIds    *[]string
	SortBy       *string
	SortOrder    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListTrailerSummariesEach iterates over all items in the ListTrailerSummaries operation.
func ListTrailerSummariesEach(c *catena.Client, ctx context.Context, opts ListTrailerSummariesPaginationOptions, yield func(telematicsapi.TrailerSummary) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.TrailerSummary, string, error) {
		req := c.Telematics().AnalyticsAPI.ListTrailerSummaries(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.TrailerIds != nil {
			req = req.TrailerIds(*opts.TrailerIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListTrailerStatusesPaginationOptions holds the options for the ListTrailerStatuses paginated operation.
type ListTrailerStatusesPaginationOptions struct {
	OnlyLatest        *bool
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	TrailerIds        *[]string
	IncludeSourceData *bool
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListTrailerStatusesEach iterates over all items in the ListTrailerStatuses operation.
func ListTrailerStatusesEach(c *catena.Client, ctx context.Context, opts ListTrailerStatusesPaginationOptions, yield func(telematicsapi.TrailerStatusRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.TrailerStatusRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListTrailerStatuses(ctx)
		if opts.OnlyLatest != nil {
			req = req.OnlyLatest(*opts.OnlyLatest)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.TrailerIds != nil {
			req = req.TrailerIds(*opts.TrailerIds)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListTrailerVehicleAssociationsPaginationOptions holds the options for the ListTrailerVehicleAssociations paginated operation.
type ListTrailerVehicleAssociationsPaginationOptions struct {
	OnlyLatest        *bool
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	TrailerIds        *[]string
	VehicleIds        *[]string
	IncludeSourceData *bool
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListTrailerVehicleAssociationsEach iterates over all items in the ListTrailerVehicleAssociations operation.
func ListTrailerVehicleAssociationsEach(c *catena.Client, ctx context.Context, opts ListTrailerVehicleAssociationsPaginationOptions, yield func(telematicsapi.TrailerVehicleAssociationRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.TrailerVehicleAssociationRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListTrailerVehicleAssociations(ctx)
		if opts.OnlyLatest != nil {
			req = req.OnlyLatest(*opts.OnlyLatest)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.TrailerIds != nil {
			req = req.TrailerIds(*opts.TrailerIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosEventCodesReferencePaginationOptions holds the options for the ListHosEventCodesReference paginated operation.
type ListHosEventCodesReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosEventCodesReferenceEach iterates over all items in the ListHosEventCodesReference operation.
func ListHosEventCodesReferenceEach(c *catena.Client, ctx context.Context, opts ListHosEventCodesReferencePaginationOptions, yield func(telematicsapi.RefHosEventCode) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefHosEventCode, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListHosEventCodesReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// GetDvirLogDefectsPaginationOptions holds the options for the GetDvirLogDefects paginated operation.
type GetDvirLogDefectsPaginationOptions struct {
	// DvirLogId is a required parameter.
	DvirLogId         string
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	IncludeSourceData *bool
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// GetDvirLogDefectsEach iterates over all items in the GetDvirLogDefects operation.
func GetDvirLogDefectsEach(c *catena.Client, ctx context.Context, opts GetDvirLogDefectsPaginationOptions, yield func(telematicsapi.DvirLogDefectRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.DvirLogDefectRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.GetDvirLogDefects(ctx, opts.DvirLogId)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListMessagesPaginationOptions holds the options for the ListMessages paginated operation.
type ListMessagesPaginationOptions struct {
	FleetIds           *[]string
	FleetRefs          *[]string
	ConnectionId       *string
	FromDatetime       *time.Time
	ToDatetime         *time.Time
	IncludeSourceData  *bool
	SenderIds          *[]string
	RecipientIds       *[]string
	SourceSenderIds    *[]string
	SourceRecipientIds *[]string
	SortBy             *string
	SortOrder          *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListMessagesEach iterates over all items in the ListMessages operation.
func ListMessagesEach(c *catena.Client, ctx context.Context, opts ListMessagesPaginationOptions, yield func(telematicsapi.MessageRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.MessageRead, string, error) {
		req := c.Telematics().DriversUsersAPI.ListMessages(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.SenderIds != nil {
			req = req.SenderIds(*opts.SenderIds)
		}
		if opts.RecipientIds != nil {
			req = req.RecipientIds(*opts.RecipientIds)
		}
		if opts.SourceSenderIds != nil {
			req = req.SourceSenderIds(*opts.SourceSenderIds)
		}
		if opts.SourceRecipientIds != nil {
			req = req.SourceRecipientIds(*opts.SourceRecipientIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListTrailerLocationsPaginationOptions holds the options for the ListTrailerLocations paginated operation.
type ListTrailerLocationsPaginationOptions struct {
	OnlyLatest        *bool
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	TrailerIds        *[]string
	VehicleIds        *[]string
	IncludeSourceData *bool
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListTrailerLocationsEach iterates over all items in the ListTrailerLocations operation.
func ListTrailerLocationsEach(c *catena.Client, ctx context.Context, opts ListTrailerLocationsPaginationOptions, yield func(telematicsapi.TrailerLocationRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.TrailerLocationRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListTrailerLocations(ctx)
		if opts.OnlyLatest != nil {
			req = req.OnlyLatest(*opts.OnlyLatest)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.TrailerIds != nil {
			req = req.TrailerIds(*opts.TrailerIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListTrailerLiveLocationsPaginationOptions holds the options for the ListTrailerLiveLocations paginated operation.
type ListTrailerLiveLocationsPaginationOptions struct {
	FleetIds     *[]string
	FleetRefs    *[]string
	ConnectionId *string
	TrailerIds   *[]string
	SourceIds    *[]string
	SortBy       *string
	SortOrder    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListTrailerLiveLocationsEach iterates over all items in the ListTrailerLiveLocations operation.
func ListTrailerLiveLocationsEach(c *catena.Client, ctx context.Context, opts ListTrailerLiveLocationsPaginationOptions, yield func(telematicsapi.TrailerLiveLocation) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.TrailerLiveLocation, string, error) {
		req := c.Telematics().AnalyticsAPI.ListTrailerLiveLocations(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.TrailerIds != nil {
			req = req.TrailerIds(*opts.TrailerIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosEventsPaginationOptions holds the options for the ListHosEvents paginated operation.
type ListHosEventsPaginationOptions struct {
	FleetIds           *[]string
	FleetRefs          *[]string
	ConnectionId       *string
	FromDatetime       *time.Time
	ToDatetime         *time.Time
	ActiveFromDatetime *time.Time
	ActiveToDatetime   *time.Time
	IncludeSourceData  *bool
	DriverIds          *[]string
	VehicleIds         *[]string
	EventTypeCodes     *[]string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosEventsEach iterates over all items in the ListHosEvents operation.
func ListHosEventsEach(c *catena.Client, ctx context.Context, opts ListHosEventsPaginationOptions, yield func(telematicsapi.HosEventRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.HosEventRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.ListHosEvents(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.ActiveFromDatetime != nil {
			req = req.ActiveFromDatetime(*opts.ActiveFromDatetime)
		}
		if opts.ActiveToDatetime != nil {
			req = req.ActiveToDatetime(*opts.ActiveToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.EventTypeCodes != nil {
			req = req.EventTypeCodes(func(in []string) []telematicsapi.HosEventTypeCodeEnum {
				out := make([]telematicsapi.HosEventTypeCodeEnum, len(in))
				for i, v := range in {
					out[i] = telematicsapi.HosEventTypeCodeEnum(v)
				}
				return out
			}(*opts.EventTypeCodes))
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListEngineLogsPaginationOptions holds the options for the ListEngineLogs paginated operation.
type ListEngineLogsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	DriverIds         *[]string
	VehicleIds        *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListEngineLogsEach iterates over all items in the ListEngineLogs operation.
func ListEngineLogsEach(c *catena.Client, ctx context.Context, opts ListEngineLogsPaginationOptions, yield func(telematicsapi.EngineLogRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.EngineLogRead, string, error) {
		req := c.Telematics().MaintenanceVehicleHealthAPI.ListEngineLogs(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosRecordOriginsReferencePaginationOptions holds the options for the ListHosRecordOriginsReference paginated operation.
type ListHosRecordOriginsReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosRecordOriginsReferenceEach iterates over all items in the ListHosRecordOriginsReference operation.
func ListHosRecordOriginsReferenceEach(c *catena.Client, ctx context.Context, opts ListHosRecordOriginsReferencePaginationOptions, yield func(telematicsapi.RefHosRecordOrigin) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefHosRecordOrigin, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListHosRecordOriginsReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosRecordStatusesReferencePaginationOptions holds the options for the ListHosRecordStatusesReference paginated operation.
type ListHosRecordStatusesReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosRecordStatusesReferenceEach iterates over all items in the ListHosRecordStatusesReference operation.
func ListHosRecordStatusesReferenceEach(c *catena.Client, ctx context.Context, opts ListHosRecordStatusesReferencePaginationOptions, yield func(telematicsapi.RefHosRecordStatus) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefHosRecordStatus, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListHosRecordStatusesReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListTrailersPaginationOptions holds the options for the ListTrailers paginated operation.
type ListTrailersPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	IncludeSourceData *bool
	TrailerIds        *[]string
	SourceIds         *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListTrailersEach iterates over all items in the ListTrailers operation.
func ListTrailersEach(c *catena.Client, ctx context.Context, opts ListTrailersPaginationOptions, yield func(telematicsapi.TrailerRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.TrailerRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListTrailers(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.TrailerIds != nil {
			req = req.TrailerIds(*opts.TrailerIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListVehicleRegionSegmentsPaginationOptions holds the options for the ListVehicleRegionSegments paginated operation.
type ListVehicleRegionSegmentsPaginationOptions struct {
	GroupBy      *string
	FleetIds     *[]string
	FleetRefs    *[]string
	ConnectionId *string
	VehicleIds   *[]string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListVehicleRegionSegmentsEach iterates over all items in the ListVehicleRegionSegments operation.
func ListVehicleRegionSegmentsEach(c *catena.Client, ctx context.Context, opts ListVehicleRegionSegmentsPaginationOptions, yield func(telematicsapi.VehicleRegionSegmentRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.VehicleRegionSegmentRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListVehicleRegionSegments(ctx)
		if opts.GroupBy != nil {
			req = req.GroupBy(*opts.GroupBy)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosViolationsPaginationOptions holds the options for the ListHosViolations paginated operation.
type ListHosViolationsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	DriverIds         *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosViolationsEach iterates over all items in the ListHosViolations operation.
func ListHosViolationsEach(c *catena.Client, ctx context.Context, opts ListHosViolationsPaginationOptions, yield func(telematicsapi.HosViolationRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.HosViolationRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.ListHosViolations(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListHosRegionsReferencePaginationOptions holds the options for the ListHosRegionsReference paginated operation.
type ListHosRegionsReferencePaginationOptions struct {
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListHosRegionsReferenceEach iterates over all items in the ListHosRegionsReference operation.
func ListHosRegionsReferenceEach(c *catena.Client, ctx context.Context, opts ListHosRegionsReferencePaginationOptions, yield func(telematicsapi.RefHosRegion) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.RefHosRegion, string, error) {
		req := c.Telematics().ReferenceDataSupportingTablesAPI.ListHosRegionsReference(ctx)
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListDvirLogDefectsPaginationOptions holds the options for the ListDvirLogDefects paginated operation.
type ListDvirLogDefectsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	DvirLogIds        *[]string
	IncludeSourceData *bool
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListDvirLogDefectsEach iterates over all items in the ListDvirLogDefects operation.
func ListDvirLogDefectsEach(c *catena.Client, ctx context.Context, opts ListDvirLogDefectsPaginationOptions, yield func(telematicsapi.DvirLogDefectRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.DvirLogDefectRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.ListDvirLogDefects(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.DvirLogIds != nil {
			req = req.DvirLogIds(*opts.DvirLogIds)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListVehicleSensorEventsPaginationOptions holds the options for the ListVehicleSensorEvents paginated operation.
type ListVehicleSensorEventsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	VehicleIds        *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListVehicleSensorEventsEach iterates over all items in the ListVehicleSensorEvents operation.
func ListVehicleSensorEventsEach(c *catena.Client, ctx context.Context, opts ListVehicleSensorEventsPaginationOptions, yield func(telematicsapi.VehicleSensorRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.VehicleSensorRead, string, error) {
		req := c.Telematics().MaintenanceVehicleHealthAPI.ListVehicleSensorEvents(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListDriverSummariesPaginationOptions holds the options for the ListDriverSummaries paginated operation.
type ListDriverSummariesPaginationOptions struct {
	FleetIds     *[]string
	FleetRefs    *[]string
	ConnectionId *string
	DriverIds    *[]string
	SourceIds    *[]string
	SortBy       *string
	SortOrder    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListDriverSummariesEach iterates over all items in the ListDriverSummaries operation.
func ListDriverSummariesEach(c *catena.Client, ctx context.Context, opts ListDriverSummariesPaginationOptions, yield func(telematicsapi.DriverSummary) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.DriverSummary, string, error) {
		req := c.Telematics().AnalyticsAPI.ListDriverSummaries(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListDriverVehicleAssociationsPaginationOptions holds the options for the ListDriverVehicleAssociations paginated operation.
type ListDriverVehicleAssociationsPaginationOptions struct {
	OnlyLatest        *bool
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	DriverIds         *[]string
	VehicleIds        *[]string
	IncludeSourceData *bool
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListDriverVehicleAssociationsEach iterates over all items in the ListDriverVehicleAssociations operation.
func ListDriverVehicleAssociationsEach(c *catena.Client, ctx context.Context, opts ListDriverVehicleAssociationsPaginationOptions, yield func(telematicsapi.DriverVehicleAssociationRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.DriverVehicleAssociationRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListDriverVehicleAssociations(ctx)
		if opts.OnlyLatest != nil {
			req = req.OnlyLatest(*opts.OnlyLatest)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListUsersPaginationOptions holds the options for the ListUsers paginated operation.
type ListUsersPaginationOptions struct {
	IsDriver          *bool
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	IncludeSourceData *bool
	UserIds           *[]string
	SourceIds         *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListUsersEach iterates over all items in the ListUsers operation.
func ListUsersEach(c *catena.Client, ctx context.Context, opts ListUsersPaginationOptions, yield func(telematicsapi.UserRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.UserRead, string, error) {
		req := c.Telematics().DriversUsersAPI.ListUsers(ctx)
		if opts.IsDriver != nil {
			req = req.IsDriver(*opts.IsDriver)
		}
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.UserIds != nil {
			req = req.UserIds(*opts.UserIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListVehiclesPaginationOptions holds the options for the ListVehicles paginated operation.
type ListVehiclesPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	IncludeSourceData *bool
	VehicleIds        *[]string
	SourceIds         *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListVehiclesEach iterates over all items in the ListVehicles operation.
func ListVehiclesEach(c *catena.Client, ctx context.Context, opts ListVehiclesPaginationOptions, yield func(telematicsapi.VehicleRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.VehicleRead, string, error) {
		req := c.Telematics().FleetOperationsTrackingAPI.ListVehicles(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SourceIds != nil {
			req = req.SourceIds(*opts.SourceIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListIftaSummariesPaginationOptions holds the options for the ListIftaSummaries paginated operation.
type ListIftaSummariesPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	VehicleIds        *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListIftaSummariesEach iterates over all items in the ListIftaSummaries operation.
func ListIftaSummariesEach(c *catena.Client, ctx context.Context, opts ListIftaSummariesPaginationOptions, yield func(telematicsapi.IftaSummaryRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.IftaSummaryRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.ListIftaSummaries(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListDvirLogsPaginationOptions holds the options for the ListDvirLogs paginated operation.
type ListDvirLogsPaginationOptions struct {
	FleetIds          *[]string
	FleetRefs         *[]string
	ConnectionId      *string
	FromDatetime      *time.Time
	ToDatetime        *time.Time
	IncludeSourceData *bool
	DriverIds         *[]string
	VehicleIds        *[]string
	SortBy            *string
	SortOrder         *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListDvirLogsEach iterates over all items in the ListDvirLogs operation.
func ListDvirLogsEach(c *catena.Client, ctx context.Context, opts ListDvirLogsPaginationOptions, yield func(telematicsapi.DvirLogRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]telematicsapi.DvirLogRead, string, error) {
		req := c.Telematics().ComplianceRegulationAPI.ListDvirLogs(ctx)
		if opts.FleetIds != nil {
			req = req.FleetIds(*opts.FleetIds)
		}
		if opts.FleetRefs != nil {
			req = req.FleetRefs(*opts.FleetRefs)
		}
		if opts.ConnectionId != nil {
			req = req.ConnectionId(*opts.ConnectionId)
		}
		if opts.FromDatetime != nil {
			req = req.FromDatetime(*opts.FromDatetime)
		}
		if opts.ToDatetime != nil {
			req = req.ToDatetime(*opts.ToDatetime)
		}
		if opts.IncludeSourceData != nil {
			req = req.IncludeSourceData(*opts.IncludeSourceData)
		}
		if opts.DriverIds != nil {
			req = req.DriverIds(*opts.DriverIds)
		}
		if opts.VehicleIds != nil {
			req = req.VehicleIds(*opts.VehicleIds)
		}
		if opts.SortBy != nil {
			req = req.SortBy(*opts.SortBy)
		}
		if opts.SortOrder != nil {
			req = req.SortOrder(*opts.SortOrder)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}
