// Code generated by catena-sdk-go pagination generator; DO NOT EDIT.

package pagination

import (
	"context"
	"time"

	catena "github.com/catenaclearing/catena-sdk-go"
	notificationsapi "github.com/catenaclearing/catena-sdk-go/gen/notifications"
	"github.com/catenaclearing/catena-sdk-go/internal/pagination"
)

// GetWebhookSubscriptionLogsPaginationOptions holds the options for the GetWebhookSubscriptionLogs paginated operation.
type GetWebhookSubscriptionLogsPaginationOptions struct {
	// WebhookId is a required parameter.
	WebhookId string
	StartDate *time.Time
	EndDate   *time.Time
	Status    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// GetWebhookSubscriptionLogsEach iterates over all items in the GetWebhookSubscriptionLogs operation.
func GetWebhookSubscriptionLogsEach(c *catena.Client, ctx context.Context, opts GetWebhookSubscriptionLogsPaginationOptions, yield func(notificationsapi.WebhookLogRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]notificationsapi.WebhookLogRead, string, error) {
		req := c.Notifications().WebhookSubscriptionsAPI.GetWebhookSubscriptionLogs(ctx, opts.WebhookId)
		if opts.StartDate != nil {
			req = req.StartDate(*opts.StartDate)
		}
		if opts.EndDate != nil {
			req = req.EndDate(*opts.EndDate)
		}
		if opts.Status != nil {
			req = req.Status(*opts.Status)
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}

// ListWebhookSubscriptionsPaginationOptions holds the options for the ListWebhookSubscriptions paginated operation.
type ListWebhookSubscriptionsPaginationOptions struct {
	EventName *string
	Status    *string
	// Cursor is the cursor for the next page.
	Cursor string
	// Size is the maximum number of items to return per page.
	Size *int
}

// ListWebhookSubscriptionsEach iterates over all items in the ListWebhookSubscriptions operation.
func ListWebhookSubscriptionsEach(c *catena.Client, ctx context.Context, opts ListWebhookSubscriptionsPaginationOptions, yield func(notificationsapi.WebhookRead) error) error {
	fetch := func(ctx context.Context, cursor string) ([]notificationsapi.WebhookRead, string, error) {
		req := c.Notifications().WebhookSubscriptionsAPI.ListWebhookSubscriptions(ctx)
		if opts.EventName != nil {
			req = req.EventName(notificationsapi.WebhookEventName(*opts.EventName))
		}
		if opts.Status != nil {
			req = req.Status(notificationsapi.StatusEnum(*opts.Status))
		}
		if cursor != "" {
			req = req.Cursor(cursor)
		} else if opts.Cursor != "" {
			req = req.Cursor(opts.Cursor)
		}
		if opts.Size != nil {
			req = req.Size(int32(*opts.Size))
		}

		resp, _, err := req.Execute()
		if err != nil {
			return nil, "", err
		}

		if resp == nil {
			return nil, "", nil
		}

		var next string
		if resp.NextPage.IsSet() && resp.NextPage.Get() != nil {
			next = *resp.NextPage.Get()
		}

		return resp.Items, next, nil
	}

	return pagination.Each(ctx, opts.Cursor, fetch, yield)
}
